/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input I01,
  input I02,
  input I03,
  input I04,
  output Q01,
  output Q02,
  output Q00,
  output Q05,
  output Q03,
  output Q04
);
  wire Q05_temp;
  assign Q05_temp = ~ (I01 | I02);
  assign Q01 = I01;
  assign Q02 = Q05_temp;
  assign Q00 = I01;
  assign Q05 = Q05_temp;
  assign Q03 = I03;
  assign Q04 = I04;
endmodule
